package sv.edu.udb.www.ProyectoPOO.entities;
// Generated Nov 17, 2018 9:49:29 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Administrador generated by hbm2java
 */
@Entity
@Table(name="administrador"
    ,catalog="bddpoo"
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Administrador  implements java.io.Serializable {


     private Integer idAdministrador;
     private Usuarios usuarios;
     private String nombresAdministrador;
     private String apellidoAdministrador;

    public Administrador() {
    }

    public Administrador(Usuarios usuarios, String nombresAdministrador, String apellidoAdministrador) {
       this.usuarios = usuarios;
       this.nombresAdministrador = nombresAdministrador;
       this.apellidoAdministrador = apellidoAdministrador;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdAdministrador", unique=true, nullable=false)
    public Integer getIdAdministrador() {
        return this.idAdministrador;
    }
    
    public void setIdAdministrador(Integer idAdministrador) {
        this.idAdministrador = idAdministrador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdUsuario", nullable=false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    
    @Column(name="NombresAdministrador", nullable=false, length=100)
    public String getNombresAdministrador() {
        return this.nombresAdministrador;
    }
    
    public void setNombresAdministrador(String nombresAdministrador) {
        this.nombresAdministrador = nombresAdministrador;
    }

    
    @Column(name="ApellidoAdministrador", nullable=false, length=100)
    public String getApellidoAdministrador() {
        return this.apellidoAdministrador;
    }
    
    public void setApellidoAdministrador(String apellidoAdministrador) {
        this.apellidoAdministrador = apellidoAdministrador;
    }




}


