package sv.edu.udb.www.ProyectoPOO.entities;
// Generated Nov 17, 2018 9:49:29 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Pattern;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="clientes"
    ,catalog="bddpoo"
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Clientes  implements java.io.Serializable {


     private Integer idCliente;
     private Usuarios usuarios;
     @NotBlank(message="Debe ingresar el nombre")
     private String nombreClientes;
     @NotBlank(message="Debe ingresar los apellidos")
     private String apellidosClientes;
     @NotBlank(message="Debe ingresar una dirección")
     private String direccion;

     @NotBlank(message="Debe ingresar el DUI")
     @Pattern(regexp = "[0-9]{8}-[0-9]" ,message="DUI con formato incorrecto")
     private String dui;
     private Set<Cupones> cuponeses = new HashSet<Cupones>(0);

    public Clientes() {
    }

	
    public Clientes(Usuarios usuarios, String nombreClientes, String apellidosClientes, String direccion, String dui) {
        this.usuarios = usuarios;
        this.nombreClientes = nombreClientes;
        this.apellidosClientes = apellidosClientes;
        this.direccion = direccion;
        this.dui = dui;
    }
    public Clientes(Usuarios usuarios, String nombreClientes, String apellidosClientes, String direccion, String dui, Set<Cupones> cuponeses) {
       this.usuarios = usuarios;
       this.nombreClientes = nombreClientes;
       this.apellidosClientes = apellidosClientes;
       this.direccion = direccion;
       this.dui = dui;
       this.cuponeses = cuponeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdCliente", unique=true, nullable=false)
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdUsuario", nullable=false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    
    @Column(name="NombreClientes", nullable=false, length=100)
    public String getNombreClientes() {
        return this.nombreClientes;
    }
    
    public void setNombreClientes(String nombreClientes) {
        this.nombreClientes = nombreClientes;
    }

    
    @Column(name="ApellidosClientes", nullable=false, length=100)
    public String getApellidosClientes() {
        return this.apellidosClientes;
    }
    
    public void setApellidosClientes(String apellidosClientes) {
        this.apellidosClientes = apellidosClientes;
    }

    
    @Column(name="Direccion", nullable=false, length=100)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="DUI", nullable=false, length=10)
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clientes")
    public Set<Cupones> getCuponeses() {
        return this.cuponeses;
    }
    
    public void setCuponeses(Set<Cupones> cuponeses) {
        this.cuponeses = cuponeses;
    }




}


