package sv.edu.udb.www.ProyectoPOO.entities;
// Generated Nov 17, 2018 9:49:29 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Cupones generated by hbm2java
 */
@Entity
@Table(name="cupones"
    ,catalog="bddpoo"
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Cupones  implements java.io.Serializable {


     private String codigoCupo;
     private Clientes clientes;
     private Estadocupon estadocupon;
     private Ofertas ofertas;
     private Date fechaCompra;
     private Date fechaCanje;

    public Cupones() {
    }

	
    public Cupones(String codigoCupo, Clientes clientes, Estadocupon estadocupon, Ofertas ofertas, Date fechaCompra) {
        this.codigoCupo = codigoCupo;
        this.clientes = clientes;
        this.estadocupon = estadocupon;
        this.ofertas = ofertas;
        this.fechaCompra = fechaCompra;
    }
    public Cupones(String codigoCupo, Clientes clientes, Estadocupon estadocupon, Ofertas ofertas, Date fechaCompra, Date fechaCanje) {
       this.codigoCupo = codigoCupo;
       this.clientes = clientes;
       this.estadocupon = estadocupon;
       this.ofertas = ofertas;
       this.fechaCompra = fechaCompra;
       this.fechaCanje = fechaCanje;
    }
   
    @Id 
    @Column(name="CodigoCupo", unique=true, nullable=false, length=13)
    public String getCodigoCupo() {
        return this.codigoCupo;
    }
    
    public void setCodigoCupo(String codigoCupo) {
        this.codigoCupo = codigoCupo;
    }
//@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdCliente", nullable=false)
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    
//@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdEstadoCupon", nullable=false)
    public Estadocupon getEstadocupon() {
        return this.estadocupon;
    }
    
    public void setEstadocupon(Estadocupon estadocupon) {
        this.estadocupon = estadocupon;
    }

    //@JsonIgnore
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdOferta", nullable=false)
    public Ofertas getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Ofertas ofertas) {
        this.ofertas = ofertas;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FechaCompra", nullable=false, length=10)
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FechaCanje", length=10)
    public Date getFechaCanje() {
        return this.fechaCanje;
    }
    
    public void setFechaCanje(Date fechaCanje) {
        this.fechaCanje = fechaCanje;
    }




}


