package sv.edu.udb.www.ProyectoPOO.entities;
// Generated Nov 17, 2018 9:49:29 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Estadooferta generated by hbm2java
 */
@Entity
@Table(name="estadooferta"
    ,catalog="bddpoo"
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Estadooferta  implements java.io.Serializable {


     private Integer idEstadoOferta;
     private String estado;
     private Set<Ofertas> ofertases = new HashSet<Ofertas>(0);

    public Estadooferta() {
    }

	
    public Estadooferta(int idEstadoOferta) {
        this.idEstadoOferta = idEstadoOferta;
    }
    public Estadooferta(String estado, Set<Ofertas> ofertases) {
       this.estado = estado;
       this.ofertases = ofertases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdEstadoOferta", unique=true, nullable=false)
    public Integer getIdEstadoOferta() {
        return this.idEstadoOferta;
    }
    
    public void setIdEstadoOferta(Integer idEstadoOferta) {
        this.idEstadoOferta = idEstadoOferta;
    }

    
    @Column(name="Estado", nullable=false, length=10)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estadooferta")
    public Set<Ofertas> getOfertases() {
        return this.ofertases;
    }
    
    public void setOfertases(Set<Ofertas> ofertases) {
        this.ofertases = ofertases;
    }




}


