package sv.edu.udb.www.ProyectoPOO.entities;
// Generated Nov 17, 2018 9:49:29 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Ofertas generated by hbm2java
 */
@Entity
@Table(name="ofertas"
    ,catalog="bddpoo"
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Ofertas  implements java.io.Serializable {


     private Integer idOferta;
     private Empresas empresas;
     private Estadooferta estadooferta;
     private String tituloOferta;
     private BigDecimal precioRegular;
     private BigDecimal precioOferta;
     private Date fechaInicio;
     private Date fechaFin;
     private Date fechaLimite;
     private Integer cantidadLimite;
     private String descripcionOferta;
     private String otrosDetalles;
     private String justificacion;
     private String urlFoto;
     private Set<Cupones> cuponeses = new HashSet<Cupones>(0);

    public Ofertas() {
    }

	
    public Ofertas(Empresas empresas, Estadooferta estadooferta, String tituloOferta, BigDecimal precioRegular, BigDecimal precioOferta, Date fechaInicio, Date fechaFin, Date fechaLimite, String descripcionOferta, String otrosDetalles) {
        this.empresas = empresas;
        this.estadooferta = estadooferta;
        this.tituloOferta = tituloOferta;
        this.precioRegular = precioRegular;
        this.precioOferta = precioOferta;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.fechaLimite = fechaLimite;
        this.descripcionOferta = descripcionOferta;
        this.otrosDetalles = otrosDetalles;
    }
    public Ofertas(Empresas empresas, Estadooferta estadooferta, String tituloOferta, BigDecimal precioRegular, BigDecimal precioOferta, Date fechaInicio, Date fechaFin, Date fechaLimite, Integer cantidadLimite, String descripcionOferta, String otrosDetalles, String justificacion, String urlFoto, Set<Cupones> cuponeses) {
       this.empresas = empresas;
       this.estadooferta = estadooferta;
       this.tituloOferta = tituloOferta;
       this.precioRegular = precioRegular;
       this.precioOferta = precioOferta;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.fechaLimite = fechaLimite;
       this.cantidadLimite = cantidadLimite;
       this.descripcionOferta = descripcionOferta;
       this.otrosDetalles = otrosDetalles;
       this.justificacion = justificacion;
       this.urlFoto = urlFoto;
       this.cuponeses = cuponeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdOferta", unique=true, nullable=false)
    public Integer getIdOferta() {
        return this.idOferta;
    }
    
    public void setIdOferta(Integer idOferta) {
        this.idOferta = idOferta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CodigoEmpresa", nullable=false)
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdEstado", nullable=false)
    public Estadooferta getEstadooferta() {
        return this.estadooferta;
    }
    
    public void setEstadooferta(Estadooferta estadooferta) {
        this.estadooferta = estadooferta;
    }

    
    @Column(name="TituloOferta", nullable=false, length=50)
    public String getTituloOferta() {
        return this.tituloOferta;
    }
    
    public void setTituloOferta(String tituloOferta) {
        this.tituloOferta = tituloOferta;
    }

    
    @Column(name="PrecioRegular", nullable=false, precision=10)
    public BigDecimal getPrecioRegular() {
        return this.precioRegular;
    }
    
    public void setPrecioRegular(BigDecimal precioRegular) {
        this.precioRegular = precioRegular;
    }

    
    @Column(name="PrecioOferta", nullable=false, precision=10)
    public BigDecimal getPrecioOferta() {
        return this.precioOferta;
    }
    
    public void setPrecioOferta(BigDecimal precioOferta) {
        this.precioOferta = precioOferta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FechaInicio", nullable=false, length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FechaFin", nullable=false, length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FechaLimite", nullable=false, length=10)
    public Date getFechaLimite() {
        return this.fechaLimite;
    }
    
    public void setFechaLimite(Date fechaLimite) {
        this.fechaLimite = fechaLimite;
    }

    
    @Column(name="CantidadLimite")
    public Integer getCantidadLimite() {
        return this.cantidadLimite;
    }
    
    public void setCantidadLimite(Integer cantidadLimite) {
        this.cantidadLimite = cantidadLimite;
    }

    
    @Column(name="DescripcionOferta", nullable=false, length=100)
    public String getDescripcionOferta() {
        return this.descripcionOferta;
    }
    
    public void setDescripcionOferta(String descripcionOferta) {
        this.descripcionOferta = descripcionOferta;
    }

    
    @Column(name="OtrosDetalles", nullable=false, length=100)
    public String getOtrosDetalles() {
        return this.otrosDetalles;
    }
    
    public void setOtrosDetalles(String otrosDetalles) {
        this.otrosDetalles = otrosDetalles;
    }

    
    @Column(name="Justificacion", length=100)
    public String getJustificacion() {
        return this.justificacion;
    }
    
    public void setJustificacion(String justificacion) {
        this.justificacion = justificacion;
    }

    
    @Column(name="Url_foto", length=100)
    public String getUrlFoto() {
        return this.urlFoto;
    }
    
    public void setUrlFoto(String urlFoto) {
        this.urlFoto = urlFoto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ofertas")
    public Set<Cupones> getCuponeses() {
        return this.cuponeses;
    }
    
    public void setCuponeses(Set<Cupones> cuponeses) {
        this.cuponeses = cuponeses;
    }




}


