package sv.edu.udb.www.ProyectoPOO.entities;
// Generated Nov 17, 2018 9:49:29 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Rubros generated by hbm2java
 */
@Entity
@Table(name="rubros"
    ,catalog="bddpoo"
    , uniqueConstraints = @UniqueConstraint(columnNames="Rubro") 
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Rubros  implements java.io.Serializable {


     private Integer idRubro;
     private String rubro;
     private Set<Empresas> empresases = new HashSet<Empresas>(0);

    public Rubros() {
    }

	
    public Rubros(String rubro) {
        this.rubro = rubro;
    }
    public Rubros(String rubro, Set<Empresas> empresases) {
       this.rubro = rubro;
       this.empresases = empresases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdRubro", unique=true, nullable=false)
    public Integer getIdRubro() {
        return this.idRubro;
    }
    
    public void setIdRubro(Integer idRubro) {
        this.idRubro = idRubro;
    }

    
    @Column(name="Rubro", unique=true, nullable=false, length=50)
    public String getRubro() {
        return this.rubro;
    }
    
    public void setRubro(String rubro) {
        this.rubro = rubro;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rubros")
    public Set<Empresas> getEmpresases() {
        return this.empresases;
    }
    
    public void setEmpresases(Set<Empresas> empresases) {
        this.empresases = empresases;
    }




}


