package sv.edu.udb.www.ProyectoPOO.entities;
// Generated Nov 17, 2018 9:49:29 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Tipousuario generated by hbm2java
 */
@Entity
@Table(name="tipousuario"
    ,catalog="bddpoo"
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Tipousuario  implements java.io.Serializable {


     private Integer idTipoUsuario;
     private String tipoUsuario;
     private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);

    public Tipousuario() {
    }

	
    public Tipousuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    
    public Tipousuario(Integer idTipoUsuario) {
    	this.idTipoUsuario=idTipoUsuario;
    }
    
    public Tipousuario(String tipoUsuario, Set<Usuarios> usuarioses) {
       this.tipoUsuario = tipoUsuario;
       this.usuarioses = usuarioses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdTipoUsuario", unique=true, nullable=false)
    public Integer getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(Integer idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }

    
    @Column(name="TipoUsuario", nullable=false, length=20)
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipousuario")
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }




}


